- hosts: localhost
  roles:
  - role: openmicroscopy.basedeps
  - role: openmicroscopy.java
  - role: openmicroscopy.omero-python-deps
  - role: openmicroscopy.ice
  - role: openmicroscopy.postgresql
    postgresql_install_server: False
  vars:
  - ice_version: "3.6"
