- hosts: localhost
  roles:
  - role: openmicroscopy.omero-server
  vars:
    ice_version: "3.6"
    ice_install_devel: False
    omero_server_database_manage: False
    omero_server_systemd_setup: False
    omero_server_system_uid: 1000
    # You can reduce the size of the image by providing the URL to a
    # precompiled Ice Python wheel
    #ice_python_wheel:
