# External Ansible roles required by this repository

- src: ome.basedeps
  version: 1.1.0

- src: ome.ice
  version: 4.0.0

- src: ome.java
  version: 2.1.0

- src: ome.omero_common
  version: 0.3.2

- name: ome.omero_server
  src: https://github.com/ome/ansible-role-omero-server/archive/d67a65f1617d1e8658444ba0f972540237f32d1c.tar.gz
  version: d67a65f1617d1e8658444ba0f972540237f32d1c

- src: ome.postgresql
  version: 3.3.1
