# External Ansible roles required by this repository

- src: ome.basedeps
  version: 1.1.0

- src: ome.ice
  version: 4.0.0

- src: ome.java
  version: 2.1.0

- src: ome.omero_common
  version: 0.3.2

- name: ome.omero_server
  src: https://github.com/ome/ansible-role-omero-server/archive/19747f05bba640df9f562fd95b1cae655ebe8e0c.tar.gz
  version: 19747f05bba640df9f562fd95b1cae655ebe8e0c

- src: ome.postgresql
  version: 3.3.1
