# External Ansible roles required by this repository

- src: ome.basedeps
  version: 1.1.0

- src: ome.ice
  version: 3.1.0

- src: ome.java
  version: 2.0.3

- src: ome.omero_common
  version: 0.3.2

- src: ome.omero_python_deps
  version: 2.0.1

- name: ome.omero_server
  src: https://github.com/ome/ansible-role-omero-server/archive/0eaeba62a9ec5f54a68522b6c79d6f5288ec927e.tar.gz
  version: 0eaeba62a9ec5f54a68522b6c79d6f5288ec927e

- src: ome.postgresql
  version: 3.3.1
