# External Ansible roles required by this repository

- src: ome.basedeps
  version: 1.1.0

- src: ome.ice
  version: 3.0.0

- src: ome.java
  version: 2.0.3

- src: ome.omego
  version: 0.1.3

- src: ome.omero_common
  version: 0.3.2

- src: ome.omero_python_deps
  version: 2.0.1

- src: ome.omero_server
  version: 2.1.0

- src: ome.postgresql
  version: 3.3.1
