# External Ansible roles required by this repository

- src: openmicroscopy.basedeps
  version: 1.0.0

- src: openmicroscopy.ice
  version: 1.0.0

- src: openmicroscopy.java
  version: 1.0.0

- src: openmicroscopy.omero-python-deps
  version: 1.0.0

- src: openmicroscopy.postgresql
  version: 1.0.0
