# External Ansible roles required by this repository

- src: ome.basedeps
  version: 1.1.0

- src: ome.ice
  version: 4.0.0

- src: ome.java
  version: 2.1.0

- src: ome.omero_common
  version: 0.3.2

- name: ome.omero_server
  src: https://github.com/joshmoore/ansible-role-omero-server/archive/94f406d552139f732d3463b223efc8e209f5024a.tar.gz
  version: 94f406d552139f732d3463b223efc8e209f5024a

- src: ome.postgresql
  version: 3.3.1
